import Head from 'next/head';
// import SearchBox from '../components/SearchBox';
import Header from '../components/Header';
import Voted from '../components/Voted';
import Footer from '../components/Footer';
import Trending from '../components/Trending';
import StaffClick from '../components/StaffClick';
import AllAdvisor from '../components/AllAdvisor';
import Recommended from '../components/Recommended';
import AllAdvisors from '../components/AllAdvisors';
import { Row, Container, Col, Card } from 'react-bootstrap';


function index() {
  return (
    <div className=''>
      <div className="somrgsaudf">
        <Header />

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container mission-nn title-misson">
          <div className="classes-module__bannerTitle">The <span style={{ fontWeight: '700' }}>clarity</span> you need <br></br>for a <span style={{ fontWeight: '700' }}>fulfilling life</span></div>
          <div className="searchboxs mt-4">
        
<input class="form-control" type="text" placeholder="Search" aria-label="Search" />
            {/* <SearchBox /> */}
            <button type="button" className="classes-module__searchButton___3drtZ">
              <div className="classes-module__searchButtonTitle___2PGdA">Find advisor</div></button>
          </div>
        </div>
      </div>
      <div className='second-content'>
        <Voted />
      </div>
      <div className=''>
        <div className="row-fluid">
          <div className="col-lg-12 col-md-10 ">
            <div className="cover-container">

              <div className="cover-item" style={{
                backgroundImage: "url(" + "https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJhZHZpc29ycy8xMDUzNy9wcm9maWxlX2ltYWdlXzE2NjM3ODk4NzMuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1ODgsImZpdCI6ImNvbnRhaW4ifX19" + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat'
              }}>
                <div className='rating-star'>
                  <div className="classes-module__ratingContainer">
                    <img src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/starIcon-c4ba539e5fdd1cf75bc335b4177e55f7.svg" />
                    <div className="classes-module__ratingText___3QgKY">4.9</div>
                  </div>
                  <div className="classes-module__playBtnContainer"><img className="classes-module__playVideoImg___2gwqV" src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/home_play-997e4f74b750c910f324de4e8fe3ceff.svg" alt="" /></div>
                </div>
                <div className='module-nicknameee'>
                  <div className=''>
                    <span className="classes-module__nickNameText">MikaShaman</span>
                  </div>
                  <div className=''>
                    <span className="classes-module__serviceTitleText">Tarot Advisor</span>
                  </div>
                </div>
                <div className="classes-module__indicatorContainer___18VUA">
                  <div className="classes-module__onlineIndicator___3TmxY"></div>
                </div>
              </div>


              <div className="cover-item" style={{
                backgroundImage: "url(" + "https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJhZHZpc29ycy8xMzY5Mi9wcm9maWxlX2ltYWdlXzE2NTk1NzYwNTUuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1ODgsImZpdCI6ImNvbnRhaW4ifX19" + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat'
              }}>
                <div className='rating-star'>
                  <div className="classes-module__ratingContainer">
                    <img src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/starIcon-c4ba539e5fdd1cf75bc335b4177e55f7.svg" />
                    <div className="classes-module__ratingText___3QgKY">4.9</div>
                  </div>
                  <div className="classes-module__playBtnContainer"><img className="classes-module__playVideoImg___2gwqV" src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/home_play-997e4f74b750c910f324de4e8fe3ceff.svg" alt="" /></div>
                </div>
                <div className='module-nicknameee'>
                  <div className=''>
                    <span className="classes-module__nickNameText">MikaShaman</span>
                  </div>
                  <div className=''>
                    <span className="classes-module__serviceTitleText">Tarot Advisor</span>
                  </div>
                </div>
                <div className="classes-module__indicatorContainer___18VUA">
                  <div className="classes-module__onlineIndicator___3T"></div>
                </div>
              </div>
              <div className="cover-item" style={{
                backgroundImage: "url(" + "https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJhZHZpc29ycy8xMDUzNy9wcm9maWxlX2ltYWdlXzE2NjM3ODk4NzMuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1ODgsImZpdCI6ImNvbnRhaW4ifX19" + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat'
              }}>
                <div className='rating-star'>
                  <div className="classes-module__ratingContainer">
                    <img src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/starIcon-c4ba539e5fdd1cf75bc335b4177e55f7.svg" />
                    <div className="classes-module__ratingText___3QgKY">4.9</div>
                  </div>
                  <div class="classes-module__playBtnContainer"><img className="classes-module__playVideoImg___2gwqV" src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/home_play-997e4f74b750c910f324de4e8fe3ceff.svg" alt="" /></div>
                </div>
                <div className='module-nicknameee'>
                  <div className=''>
                    <span className="classes-module__nickNameText">MikaShaman</span>
                  </div>
                  <div className=''>
                    <span className="classes-module__serviceTitleText">Tarot Advisor</span>
                  </div>
                </div>
                <div className="classes-module__indicatorContainer___18VUA">
                  <div className="classes-module__onlineIndicator___3T"></div>
                </div>
              </div>
              <div className="cover-item" style={{
                backgroundImage: "url(" + "https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJhZHZpc29ycy8xMzY5Mi9wcm9maWxlX2ltYWdlXzE2NTk1NzYwNTUuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1ODgsImZpdCI6ImNvbnRhaW4ifX19" + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat'
              }}>
                <div className='rating-star'>
                  <div className="classes-module__ratingContainer">
                    <img src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/starIcon-c4ba539e5fdd1cf75bc335b4177e55f7.svg" />
                    <div className="classes-module__ratingText___3QgKY">4.9</div>
                  </div>
                  <div className="classes-module__playBtnContainer"><img className="classes-module__playVideoImg___2gwqV" src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/home_play-997e4f74b750c910f324de4e8fe3ceff.svg" alt="" /></div>
                </div>
                <div className='module-nicknameee'>
                  <div className=''>
                    <span className="classes-module__nickNameText">MikaShaman</span>
                  </div>
                  <div className=''>
                    <span className="classes-module__serviceTitleText">Tarot Advisor</span>
                  </div>
                </div>
                <div className="classes-module__indicatorContainer___18VUA">
                  <div className="classes-module__onlineIndicator___3T"></div>
                </div>
              </div>
              <div className="cover-item" style={{
                backgroundImage: "url(" + "https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJhZHZpc29ycy8xMDUzNy9wcm9maWxlX2ltYWdlXzE2NjM3ODk4NzMuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1ODgsImZpdCI6ImNvbnRhaW4ifX19" + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat'
              }}>
                <div className='rating-star'>
                  <div className="classes-module__ratingContainer">
                    <img src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/starIcon-c4ba539e5fdd1cf75bc335b4177e55f7.svg" />
                    <div className="classes-module__ratingText___3QgKY">4.9</div>
                  </div>
                  <div className="classes-module__playBtnContainer"><img className="classes-module__playVideoImg___2gwqV" src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/home_play-997e4f74b750c910f324de4e8fe3ceff.svg" alt="" /></div>
                </div>
                <div className='module-nicknameee'>
                  <div className=''>
                    <span className="classes-module__nickNameText">MikaShaman</span>
                  </div>
                  <div className=''>
                    <span className="classes-module__serviceTitleText">Tarot Advisor</span>
                  </div>
                </div>
                <div className="classes-module__indicatorContainer___18VUA">
                  <div className="classes-module__onlineIndicator___3T"></div>
                </div>
              </div>
              <div className="cover-item" style={{
                backgroundImage: "url(" + "https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJhZHZpc29ycy8xMzY5Mi9wcm9maWxlX2ltYWdlXzE2NTk1NzYwNTUuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1ODgsImZpdCI6ImNvbnRhaW4ifX19" + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat'
              }}>
                <div className='rating-star'>
                  <div className="classes-module__ratingContainer">
                    <img src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/starIcon-c4ba539e5fdd1cf75bc335b4177e55f7.svg" />
                    <div className="classes-module__ratingText___3QgKY">4.9</div>
                  </div>
                  <div className="classes-module__playBtnContainer"><img className="classes-module__playVideoImg___2gwqV" src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/home_play-997e4f74b750c910f324de4e8fe3ceff.svg" alt="" /></div>
                </div>
                <div className='module-nicknameee'>
                  <div className=''>
                    <span className="classes-module__nickNameText">MikaShaman</span>
                  </div>
                  <div className=''>
                    <span className="classes-module__serviceTitleText">Tarot Advisor</span>
                  </div>
                </div>
                <div className="classes-module__indicatorContainer___18VUA">
                  <div className="classes-module__onlineIndicator___3T"></div>
                </div>
              </div>
              <div className="cover-item" style={{
                backgroundImage: "url(" + "https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJhZHZpc29ycy8xMDUzNy9wcm9maWxlX2ltYWdlXzE2NjM3ODk4NzMuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1ODgsImZpdCI6ImNvbnRhaW4ifX19" + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat'
              }}>
                <div className='rating-star'>
                  <div className="classes-module__ratingContainer">
                    <img src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/starIcon-c4ba539e5fdd1cf75bc335b4177e55f7.svg" />
                    <div className="classes-module__ratingText___3QgKY">4.9</div>
                  </div>
                  <div className="classes-module__playBtnContainer"><img className="classes-module__playVideoImg___2gwqV" src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/home_play-997e4f74b750c910f324de4e8fe3ceff.svg" alt="" /></div>
                </div>
                <div className='module-nicknameee'>
                  <div className=''>
                    <span className="classes-module__nickNameText">MikaShaman</span>
                  </div>
                  <div className=''>
                    <span className="classes-module__serviceTitleText">Tarot Advisor</span>
                  </div>
                </div>
                <div className="classes-module__indicatorContainer___18VUA">
                  <div className="classes-module__onlineIndicator___3T"></div>
                </div>
              </div>

              <div className="cover-item" style={{
                backgroundImage: "url(" + "https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJhZHZpc29ycy8xMzY5Mi9wcm9maWxlX2ltYWdlXzE2NTk1NzYwNTUuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1ODgsImZpdCI6ImNvbnRhaW4ifX19" + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat'
              }}>
                <div className='rating-star'>
                  <div className="classes-module__ratingContainer">
                    <img src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/starIcon-c4ba539e5fdd1cf75bc335b4177e55f7.svg" />
                    <div className="classes-module__ratingText___3QgKY">4.9</div>
                  </div>
                  <div className="classes-module__playBtnContainer"><img className="classes-module__playVideoImg___2gwqV" src="https://www.purplegarden.co/packs/media/src/app/components/advisor_avatar/img/home_play-997e4f74b750c910f324de4e8fe3ceff.svg" alt="" /></div>
                </div>
                <div className='module-nicknameee'>
                  <div className=''>
                    <span className="classes-module__nickNameText">MikaShaman</span>
                  </div>
                  <div className=''>
                    <span className="classes-module__serviceTitleText">Tarot Advisor</span>
                  </div>
                </div>
                <div className="classes-module__indicatorContainer___18VUA">
                  <div className="classes-module__onlineIndicator___3T"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className='third-section mt-5'>
        <Container>
          <Row>
            <Col xs={12} md={12} >
              <div className="sp-page sp-css-target sp-text-wrapper">
                <div className="classes-module__advisorTitle text-left">
                  <div className='forword-all'>
                    <div className='voted-fdresad'>
                      <img src="trending.jpg" alt="" width="40" height="40px" />
                      <h2 className="classes-module__advisorTitleText">Trending</h2>
                    </div>
                    <div className=''>
                      <a className="classes-module__seeAllBtn___8PIxG" href="/most-accurate-psychics">All</a>
                    </div>
                  </div>
                  <Card.Text>Our exclusive list of psychics advisors whom our users acknowledged as being most accurate in their advice and guidance. These advisors who are ready to enlighten, inspire, and empower you – are all vetted and voted for by people like you. Our top-accuracy advisors cover a wide range of services including love readings, mediumship, tarot cards, career advice, and more.</Card.Text>
                </div>
              </div>
              <Row>
                <Trending />
              </Row>
              <Row className='fourth-cjhtgdfr mt-5'>
                <div className="column" >

                  <a className="classes-module__speciality___e9DaP"
                    href="/love_readings">
                    <img className="classes-module__specialityImg____xNe3" src="https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJwZ19jYXRlZ29yaWVzL2xvdmUucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7ImZpdCI6ImNvbnRhaW4ifX19" />
                    <div className="classes-module__specialityName___6bt_Q"><span>Love </span>
                      <span>readings</span>
                    </div>
                  </a>
                </div>
                <div className="column" >
                  <a className="classes-module__speciality___e9DaP"
                    href="/love_readings">
                    <img className="classes-module__specialityImg____xNe3" src="https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJwZ19jYXRlZ29yaWVzL2xvdmUucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7ImZpdCI6ImNvbnRhaW4ifX19" />
                    <div className="classes-module__specialityName___6bt_Q"><span>Love </span>
                      <span>readings</span>
                    </div>
                  </a>
                </div>
                <div className="column" >
                  <a className="classes-module__speciality___e9DaP"
                    href="/love_readings">
                    <img className="classes-module__specialityImg____xNe3" src="https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJwZ19jYXRlZ29yaWVzL2xvdmUucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7ImZpdCI6ImNvbnRhaW4ifX19" />
                    <div className="classes-module__specialityName___6bt_Q"><span>Love </span>
                      <span>readings</span>
                    </div>
                  </a>
                </div>
                <div className="column" >
                  <a className="classes-module__speciality___e9DaP"
                    href="/love_readings">
                    <img className="classes-module__specialityImg____xNe3" src="https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJwZ19jYXRlZ29yaWVzL2xvdmUucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7ImZpdCI6ImNvbnRhaW4ifX19" />
                    <div className="classes-module__specialityName___6bt_Q"><span>Love </span>
                      <span>readings</span>
                    </div>
                  </a>
                </div>
                <div className="column" >
                  <a className="classes-module__speciality___e9DaP"
                    href="/love_readings">
                    <img className="classes-module__specialityImg____xNe3" src="https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJwZ19jYXRlZ29yaWVzL2xvdmUucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7ImZpdCI6ImNvbnRhaW4ifX19" />
                    <div className="classes-module__specialityName___6bt_Q"><span>Love </span>
                      <span>readings</span>
                    </div>
                  </a>
                </div>
                <div className="column" >
                  <a className="classes-module__speciality___e9DaP"
                    href="/love_readings">
                    <img className="classes-module__specialityImg____xNe3" src="https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJwZ19jYXRlZ29yaWVzL2xvdmUucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7ImZpdCI6ImNvbnRhaW4ifX19" />
                    <div className="classes-module__specialityName___6bt_Q"><span>Love </span>
                      <span>readings</span>
                    </div>
                  </a>
                </div>
                <div className="column" >
                  <a className="classes-module__speciality___e9DaP"
                    href="/love_readings">
                    <img className="classes-module__specialityImg____xNe3" src="https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJwZ19jYXRlZ29yaWVzL2xvdmUucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7ImZpdCI6ImNvbnRhaW4ifX19" />
                    <div className="classes-module__specialityName___6bt_Q"><span>Love </span>
                      <span>readings</span>
                    </div>
                  </a>
                </div>
                <div className="column" >
                  <a className="classes-module__speciality___e9DaP"
                    href="/love_readings">
                    <img className="classes-module__specialityImg____xNe3" src="https://d1xfvknfftsbde.cloudfront.net/eyJidWNrZXQiOiJwdXJwbGUtb2NlYW4iLCJrZXkiOiJwZ19jYXRlZ29yaWVzL2xvdmUucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7ImZpdCI6ImNvbnRhaW4ifX19" />
                    <div className="classes-module__specialityName___6bt_Q"><span>Love </span>
                      <span>readings</span>
                    </div>
                  </a>
                </div>
              </Row>
              <Row>
                <Col xs={12} md={12} >
                  <div className="classes-module__allAdvisorsButtonContainer___3WOAW">
                    <div className="classes-module__allAdvisorsButtonTextBrowser___2Cqug">Didn’t find what you were looking for? See all of our finest advisors.</div>
                    <div className="classes-module__allAdvisorsButtonTextMobile___209Qg">Didn’t find what you were looking for?</div>
                    <a className="classes-module__allAdvisorsButton___2QG_L" href="/psychics">
                      <img src="/packs/media/src/app/components/advisors_list/img/see_more_btn-5ae159cab1974bd6374ed8309ba73442.svg" class="classes-module__seeMoreBtnImg___3XM6S" alt="" />All advisors</a>
                  </div>
                </Col>
              </Row>
            </Col>
            <Container>
              <Row>
                <Col>
                  <StaffClick />
                </Col>
              </Row>
            </Container>
          </Row>
        </Container>
      </div>
      <div className=''>
        <AllAdvisor />
      </div>
      <div className=''>
        <Recommended />
      </div>
      <div className=''>
        <AllAdvisors />
      </div>
      <div className='last-buttonhdgf'>
        <div class="classes-module__homePageAllAdvisors___1IPY6">
          <div class="classes-module__bottomButtonContainer___2uAnH">
            <a class="classes-module__bottomButton___1kRis" href="/psychics">
              <img src="https://www.purplegarden.co/packs/media/src/app/components/advisors_list/img/see_more_btn-5ae159cab1974bd6374ed8309ba73442.svg" class="classes-module__seeMoreBtnImg___2QgGx" alt="" />See more advisors</a>
          </div>
        </div>
      </div>
      <Footer />
      
    </div>

  )
}
export default index


